[[pages]]
path = "pages/business_problem.py"
name = "Problema de NegÃ³cio"
icon = "ğŸ“Š"

[[pages]]
path = "pages/objective.py"
name = "Objetivo"
icon = "ğŸ¯"

[[pages]]
path = "pages/solution.py"
name = "SoluÃ§Ã£o Proposta"
icon = "ğŸ“ˆ"

[[pages]]
path = "pages/match_candidates1.py"
name = "Agente IA de SeleÃ§Ã£o de Candidatos"
icon = "ğŸ”"

[[pages]]
path = "pages/challenges.py"
name = "Desafios e oportunidade de melhoria"
icon = "ğŸ”"
