[[pages]]
path = "pages/business_problem.py"
name = "Problema de NegÃ³cio"
icon = "ğŸ“Š"

[[pages]]
path = "pages/objectives.py"
name = "Objetivo"
icon = "ğŸ¯"

[[pages]]
path = "pages/solution.py"
name = "SoluÃ§Ã£o Proposta"
icon = "ğŸ“ˆ"
